name: flutter_clean_architecture_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  dartz: ^0.10.1
  flutter_bloc: ^8.1.6
  http: ^1.2.2
  shared_preferences: ^2.3.5
  get_it: ^8.0.3
  sqflite: ^2.4.1
  path_provider: ^2.1.5
  path: ^1.9.0
  connectivity_plus: ^6.1.1
  flutter_localizations:
    sdk: flutter
  cached_network_image: ^3.4.1
  flutter_blurhash: ^0.8.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/
